/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bangBlastsSol from "./BangBlasts.sol";
export type { bangBlastsSol };
export type { Lock } from "./Lock";
